Repository ZauJulio/ByteSeridoClasses, pull requests merged in 2021-07, with the labels that each got.

#1 Add hotfix to readme links
  README.md
Labels: wontfix

#2 Complete countdown
  examples/react/countdown/src/App.js
  examples/react/countdown/src/App.scss
Labels: enhancement

#3 Ctx api example
  README.md
  examples/react/ctx-api/.gitignore
  examples/react/ctx-api/README.md
  examples/react/ctx-api/package.json
  examples/react/ctx-api/public/index.html
  examples/react/ctx-api/src/Home.tsx
  examples/react/ctx-api/src/components/Countdown/index.tsx
  examples/react/ctx-api/src/components/Countdown/styles.scss
  examples/react/ctx-api/src/components/Countdown2/index.tsx
  examples/react/ctx-api/src/components/Countdown2/styles.scss
  examples/react/ctx-api/src/contexts/CountdownCtx/context.tsx
  examples/react/ctx-api/src/contexts/CountdownCtx/index.tsx
  examples/react/ctx-api/src/index.tsx
  examples/react/ctx-api/src/react-app-env.d.ts
  examples/react/ctx-api/src/styles/App.css
  examples/react/ctx-api/src/styles/index.css
  examples/react/ctx-api/tsconfig.json
  examples/react/ctx-api/yarn.lock
Labels: documentation, enhancement

#4 Complete ctx-api example
  examples/react/ctx-api++/.gitignore
  examples/react/ctx-api++/README.md
  examples/react/ctx-api++/package.json
  examples/react/ctx-api++/public/index.html
  examples/react/ctx-api++/src/Home.tsx
  examples/react/ctx-api++/src/components/Countdown/index.tsx
  examples/react/ctx-api++/src/components/Countdown/styles.scss
  examples/react/ctx-api++/src/contexts/CountdownCtx/context.tsx
  examples/react/ctx-api++/src/contexts/CountdownCtx/index.tsx
  examples/react/ctx-api++/src/index.tsx
  examples/react/ctx-api++/src/react-app-env.d.ts
  examples/react/ctx-api++/src/shared/button.styles.tsx
  examples/react/ctx-api++/src/styles/App.css
  examples/react/ctx-api++/src/styles/index.css
  examples/react/ctx-api++/tsconfig.json
  examples/react/ctx-api++/yarn.lock
Labels: documentation, enhancement

#5 Update README.md
  README.md
Labels: documentation
